modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Cheaterpaul/Blur/issues"
displayURL="https://github.com/Cheaterpaul/Blur/"
authors="Cheaterpaul"
logoFile="blur_logo.png"
license="MIT"

[[mods]]
modId="blur"
version="${version}"
displayName="Blur"
description="Adds a blurry background when viewing GUIs"

[[dependencies.blur]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blur]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"