modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Cheaterpaul/ReBlured/issues"
displayURL="https://github.com/Cheaterpaul/ReBlured/"
authors="Cheaterpaul"
logoFile="blur_logo.png"
license="MIT"

[[mods]]
modId="reblured"
version="${version}"
displayName="ReBlured"
description="Adds a blurry background when viewing GUIs"

[[dependencies.reblured]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.reblured]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"