modLoader="javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "${mod_issue_tracker_url}"
displayURL="https://github.com/Cheaterpaul/ReBlured/"
authors="Cheaterpaul"
logoFile="blur_logo.png"
license = "${mod_license}"
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description= '''${mod_description}'''
[[mixins]]
config = "reblured.mixins.json"
[[dependencies.reblured]]
    modId="neoforge"
    type="required"
    versionRange= "${forge_version_range}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.reblured]]
    modId="minecraft"
    type="required"
    versionRange= "${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"